---
title: "best model coefficients"
output: word_document
date: "`r Sys.Date()`"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}


library(tidyverse)
library(here)
library(AICcmodavg)
library(birdnames)
library(flextable)
library(ftExtra)
library(officer)

custom_bird_list <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/my_R_general/birdnames_support/data/custom_bird_list")


source("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/core_monitoring_research/HEP/hep_analyses/how_are_the_egrets_doing/code/ms_analysis/hep_trend_utilities.R")


options(scipen = 999)


spp_subreg <- readRDS(here("data/spp_subreg")) %>%
  mutate(species = factor(species, levels = c("GREG", "GBHE", "SNEG", "BCNH"))) %>% 
  full_join(subreg_key) %>% 
  arrange(species, subreg.name) 

```

```{r}


# zspp_subreg = "GREG_All"


get_best_mod_dev_expl <- function(zspp_subreg) {
zmods <- readRDS(here("fitted_models/spp_subreg_mods"))[[zspp_subreg]]

best_mod_name <- aictab(zmods) %>% 
  data.frame() %>% 
  filter(Delta_AICc == 0)

best_mod <- zmods[[best_mod_name$Modnames]]

dev_expl <- data.frame(dev.expl = 100*with(summary(best_mod), 1 - deviance/null.deviance))  %>% 
  bind_cols(Modnames = names(zmods[best_mod_name$Modnames]),
            spp.subreg = zspp_subreg)

return(dev_expl)
}



get_best_mod_coefs <- function(zspp_subreg) {
zmods <- readRDS(here("fitted_models/spp_subreg_mods"))[[zspp_subreg]]

best_mod_name <- aictab(zmods) %>% 
  data.frame() %>% 
  filter(Delta_AICc == 0)

best_mod <- zmods[[best_mod_name$Modnames]]


  coefs <- coef(best_mod) %>%
    data.frame() %>% 
    rename("coef" = 1) %>% 
    rownames_to_column("variable") 
  
  ci  <- confint(best_mod) %>%
    data.frame()
# ci for intercept only model come out different than for other models  
if(names(zmods[best_mod_name$Modnames]) == "intercept") {
  ci <- ci %>%
  rownames_to_column("zci") %>% 
    rename(value = 2) %>% 
    pivot_wider(names_from = zci) %>% 
  rename(lci = 1, uci = 2) %>% 
    mutate(variable = "(Intercept)")
 } else { 
ci <- ci %>% 
  rownames_to_column("variable") %>% 
  rename(lci = 2, uci = 3)
 }
  
  coef_ci <- full_join(coefs, ci) %>%
    mutate(spp.subreg = zspp_subreg,
           Modnames = names(zmods[best_mod_name$Modnames]))
  return(coef_ci)
}


all_coef_ci <- map_df(spp_subreg$spp.subreg, get_best_mod_coefs) 
all_dev_expl <- map_df(spp_subreg$spp.subreg, get_best_mod_dev_expl) 


all_coef_ci_clean_names <- all_coef_ci %>% 
  mutate(variable = str_replace(variable, "poly\\(", ""),
         variable = str_replace(variable, ", 2\\)1", ""),
         variable = str_replace(variable, ", 2\\)2", "2"),
         variable = str_replace(variable, "wt.lag.subreg.", ""),
         variable = str_replace(variable, "\\(Intercept\\)", "Intercept"),
         variable = fix_mod_name_out(variable)) %>% 
  filter(variable != "Intercept")

all_coef_ci_wide <- all_coef_ci_clean_names %>% 
  mutate(across(c(coef, lci, uci), ~format(round(., 3), nsmall = 3, trim=TRUE)),
         coef.ci = paste(coef, " (", lci, ", ", uci, ")", sep = "")) %>% 
  pivot_wider(id_cols = c(spp.subreg, Modnames), names_from = variable, values_from = coef.ci) %>% 
  full_join(all_dev_expl) %>% 
  mutate(dev.expl = format(round(dev.expl, 2), nsmall = 2, trim=TRUE)) %>%
  separate(spp.subreg, c("species", "subregion"), sep = "_") %>% 
  left_join(subreg_key) %>% 
  full_join(spp_subreg) %>% 
  mutate(common.name = translate_bird_names(species, "alpha.code", "common.name"),
         species = factor(species, levels = levels(spp_subreg$species))) %>%  
  arrange(species, subreg.name)
  
```


```{r}
all_coef_ci_wide %>% 
  filter(as.numeric(dev.expl) > 0) %>% 
  nrow()


```

Table XX. Coefficient values for the best supported models (lowest AICc values) for estimating heron and egret abundance in the San Francisco Bay area ("Entire study area"), California, and 10 subregions, 1995-2019. Shown also for each model is the percent deviance explained (% Dev. explained).

```{r}
all_coef_ci_wide %>% 
  mutate(common.name = ifelse(subregion == "All", common.name, "")) %>% 
  select(common.name, subreg.name, Year, `Year^2^`, Rain, `Rain^2^`, dev.expl) %>% 
  flextable() %>% 
  autofit()%>% 
    set_header_labels(common.name = "Species",
                      subreg.name = "Subregion",
                    dev.expl = "% Dev.\nexplained")%>% 
  align(j = 3:7, align = "center", part = "all") %>% 
  fit_to_width(max_width = 7.5) %>%
  border(i = c(9, 20, 28), part = "body", border.bottom = fp_border(color = "black")) %>% 
  colformat_md() 


```
